M48
; DRILL file {KiCad (6.0.7)} date Thu Nov 10 23:39:33 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-11-10T23:39:33-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.600
%
G90
G05
T1
X122.075Y-58.444
T1
X122.075Y-64.319G85X122.075Y-64.569
G05
T0
M30
